/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'all-pages': AllPage;
    cards: Card;
    news: News;
    translations: Translation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'all-pages': AllPagesSelect<false> | AllPagesSelect<true>;
    cards: CardsSelect<false> | CardsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    translations: TranslationsSelect<false> | TranslationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'site-subfooter': SiteSubfooter;
    'site-footer': SiteFooter;
    'site-header': SiteHeader;
  };
  globalsSelect: {
    'site-subfooter': SiteSubfooterSelect<false> | SiteSubfooterSelect<true>;
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "all-pages".
 */
export interface AllPage {
  id: number;
  searchIndex?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  title: string;
  meta?: {
    /**
     * The title seen in search engines. Ideally < 60 chars.
     */
    title?: string | null;
    /**
     * The summary seen in search results. Ideally < 160 chars.
     */
    description?: string | null;
  };
  /**
   * Select a parent page to nest this page under (e.g., About > What We Do)
   */
  parent?: (number | null) | AllPage;
  /**
   * Auto-generated from title. Full path will include parent slugs.
   */
  slug: string;
  fullPath?: string | null;
  layout: (
    | {
        slides: {
          title?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          button: {
            text: string;
            linkType: 'internal' | 'external' | 'file';
            internalLink?:
              | ({
                  relationTo: 'all-pages';
                  value: number | AllPage;
                } | null)
              | ({
                  relationTo: 'news';
                  value: number | News;
                } | null);
            externalLink?: string | null;
            /**
             * Upload a file for users to download.
             */
            fileLink?: (number | null) | Media;
          };
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroSwiper';
      }
    | {
        title?: string | null;
        highlights: {
          title?: string | null;
          /**
           * Upload an icon image for this highlight.
           */
          icon?: (number | null) | Media;
          /**
           * Upload a background image for this highlight.
           */
          backgroundImage?: (number | null) | Media;
          linkType: 'internal' | 'external' | 'file' | 'mailto';
          internalLink?: {
            relationTo: 'all-pages';
            value: number | AllPage;
          } | null;
          /**
           * Enter the full URL, e.g. https://example.com
           */
          externalLink?: string | null;
          /**
           * Upload a file for users to download.
           */
          fileLink?: (number | null) | Media;
          /**
           * Enter the email address to link to.
           */
          mailtoLink?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'highlights';
      }
    | {
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heroImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroImage';
      }
    | {
        cards: {
          title?: string | null;
          /**
           * Select one or more cards to display
           */
          cardBlocks?: (number | Card)[] | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardGallery';
      }
    | {
        pageTitle?: string | null;
        mapEmbedUrl: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'locationMap';
      }
    | {
        title?: string | null;
        columns?:
          | {
              textContent?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        sectionTitle?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        links?:
          | {
              label: string;
              /**
               * Upload an icon image for this link.
               */
              icon?: (number | null) | Media;
              linkType: 'internal' | 'external' | 'file';
              internalLink?: {
                relationTo: 'all-pages';
                value: number | AllPage;
              } | null;
              /**
               * Enter the full URL, e.g. https://example.com
               */
              externalLink?: string | null;
              /**
               * Upload a file for users to download.
               */
              fileLink?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeIntro';
      }
    | {
        title?: string | null;
        /**
         * Upload an image for this block.
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'singularImage';
      }
    | {
        title?: string | null;
        textContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textImage';
      }
    | {
        linkType: 'internal' | 'external' | 'file' | 'mailto';
        internalLink?: {
          relationTo: 'all-pages';
          value: number | AllPage;
        } | null;
        /**
         * Enter the full URL, e.g. https://example.com
         */
        externalLink?: string | null;
        /**
         * Upload a file for users to download.
         */
        fileLink?: (number | null) | Media;
        /**
         * Enter the email address to link to.
         */
        mailtoLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'link';
      }
    | {
        sectionTitle?: string | null;
        buttontext?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        slides: {
          title?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          button: {
            text: string;
            linkType: 'internal' | 'external';
            internalLink?:
              | ({
                  relationTo: 'all-pages';
                  value: number | AllPage;
                } | null)
              | ({
                  relationTo: 'news';
                  value: number | News;
                } | null);
            externalLink?: string | null;
          };
          image: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'pressSwiper';
      }
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        videoSource?: ('upload' | 'youtube') | null;
        /**
         * Upload a video file when Video Source is Upload Video.
         */
        video?: (number | null) | Media;
        /**
         * Paste a YouTube link, e.g. https://www.youtube.com/watch?v=... or https://youtu.be/...
         */
        youtubeUrl?: string | null;
        sideline?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        title?: string | null;
        /**
         * Upload an image for this block.
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dsmImage';
      }
    | {
        title?: string | null;
        /**
         * Upload an image for this block.
         */
        image?: (number | null) | Media;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dsmTextImage';
      }
    | {
        title?: string | null;
        resources?:
          | {
              /**
               * Upload an image for this resource.
               */
              image?: (number | null) | Media;
              caption?: string | null;
              linkText?: string | null;
              linkType: 'internal' | 'external' | 'file';
              internalLink?: {
                relationTo: 'all-pages';
                value: number | AllPage;
              } | null;
              /**
               * Enter the full URL, e.g. https://example.com
               */
              externalLink?: string | null;
              /**
               * Upload a file for users to download.
               */
              fileLink?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dsmResources';
      }
    | {
        title?: string | null;
        textContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        linkText?: string | null;
        linkType: 'internal' | 'external' | 'file';
        internalLink?: {
          relationTo: 'all-pages';
          value: number | AllPage;
        } | null;
        /**
         * Enter the full URL, e.g. https://example.com
         */
        externalLink?: string | null;
        /**
         * Upload a file for users to download.
         */
        fileLink?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'textImageLink';
      }
    | {
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        cards: {
          title?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[];
        sideImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'taqati';
      }
    | {
        content?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'plainText';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  searchIndex?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  title?: string | null;
  date?: string | null;
  /**
   * Select the main page this detail page belongs to
   */
  parentPage?: (number | null) | AllPage;
  /**
   * Auto-generated from the title. Full path will include the parent page slug.
   */
  slug: string;
  fullPath?: string | null;
  /**
   * Upload image for this card.
   */
  image?: (number | null) | Media;
  /**
   * Short description for this detail page
   */
  shortDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards".
 */
export interface Card {
  id: number;
  searchIndex?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for this card. Used to generate the slug.
   */
  title: string;
  /**
   * Upload image for this card.
   */
  image?: (number | null) | Media;
  /**
   * Short description for this detail page
   */
  shortDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  linkType: 'internal' | 'external' | 'file' | 'mailto';
  internalLink?: {
    relationTo: 'all-pages';
    value: number | AllPage;
  } | null;
  /**
   * Enter the full URL, e.g. https://example.com
   */
  externalLink?: string | null;
  /**
   * Upload a file for users to download.
   */
  fileLink?: (number | null) | Media;
  /**
   * Enter the email address to link to.
   */
  mailtoLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations".
 */
export interface Translation {
  id: number;
  key?: string | null;
  en_value?: string | null;
  ar_value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'all-pages';
        value: number | AllPage;
      } | null)
    | ({
        relationTo: 'cards';
        value: number | Card;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'translations';
        value: number | Translation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "all-pages_select".
 */
export interface AllPagesSelect<T extends boolean = true> {
  searchIndex?:
    | T
    | {
        text?: T;
        id?: T;
      };
  title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  parent?: T;
  slug?: T;
  fullPath?: T;
  layout?:
    | T
    | {
        heroSwiper?:
          | T
          | {
              slides?:
                | T
                | {
                    title?: T;
                    description?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          linkType?: T;
                          internalLink?: T;
                          externalLink?: T;
                          fileLink?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlights?:
          | T
          | {
              title?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    backgroundImage?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    fileLink?: T;
                    mailtoLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        heroImage?:
          | T
          | {
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        cardGallery?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    cardBlocks?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        locationMap?:
          | T
          | {
              pageTitle?: T;
              mapEmbedUrl?: T;
              id?: T;
              blockName?: T;
            };
        homeIntro?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    textContent?: T;
                    id?: T;
                  };
              sectionTitle?: T;
              links?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    fileLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        singularImage?:
          | T
          | {
              title?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              title?: T;
              textContent?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        link?:
          | T
          | {
              linkType?: T;
              internalLink?: T;
              externalLink?: T;
              fileLink?: T;
              mailtoLink?: T;
              id?: T;
              blockName?: T;
            };
        pressSwiper?:
          | T
          | {
              sectionTitle?: T;
              buttontext?: T;
              slides?:
                | T
                | {
                    title?: T;
                    description?: T;
                    button?:
                      | T
                      | {
                          text?: T;
                          linkType?: T;
                          internalLink?: T;
                          externalLink?: T;
                        };
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              title?: T;
              description?: T;
              videoSource?: T;
              video?: T;
              youtubeUrl?: T;
              sideline?: T;
              id?: T;
              blockName?: T;
            };
        dsmImage?:
          | T
          | {
              title?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        dsmTextImage?:
          | T
          | {
              title?: T;
              image?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        dsmResources?:
          | T
          | {
              title?: T;
              resources?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    linkText?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    fileLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textImageLink?:
          | T
          | {
              title?: T;
              textContent?: T;
              image?: T;
              linkText?: T;
              linkType?: T;
              internalLink?: T;
              externalLink?: T;
              fileLink?: T;
              id?: T;
              blockName?: T;
            };
        taqati?:
          | T
          | {
              title?: T;
              description?: T;
              cards?:
                | T
                | {
                    title?: T;
                    image?: T;
                    id?: T;
                  };
              sideImage?: T;
              id?: T;
              blockName?: T;
            };
        plainText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cards_select".
 */
export interface CardsSelect<T extends boolean = true> {
  searchIndex?:
    | T
    | {
        text?: T;
        id?: T;
      };
  title?: T;
  image?: T;
  shortDescription?: T;
  linkType?: T;
  internalLink?: T;
  externalLink?: T;
  fileLink?: T;
  mailtoLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  searchIndex?:
    | T
    | {
        text?: T;
        id?: T;
      };
  title?: T;
  date?: T;
  parentPage?: T;
  slug?: T;
  fullPath?: T;
  image?: T;
  shortDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "translations_select".
 */
export interface TranslationsSelect<T extends boolean = true> {
  key?: T;
  en_value?: T;
  ar_value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-subfooter".
 */
export interface SiteSubfooter {
  id: number;
  sections: {
    contactMethods?: {
      method?:
        | {
            icon?: (number | null) | Media;
            type?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
          }[]
        | null;
    };
    quote?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'contact-quote';
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: number;
  sections: (
    | {
        images?:
          | {
              image?: (number | null) | Media;
              linkType: 'internal' | 'external';
              internalLink?: {
                relationTo: 'all-pages';
                value: number | AllPage;
              } | null;
              /**
               * Enter the full URL, e.g. https://example.com
               */
              externalLink?: string | null;
              id?: string | null;
            }[]
          | null;
        text?:
          | {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerImagesText';
      }
    | {
        bottomfooter?: {
          text?:
            | {
                text?: string | null;
                linkType: 'internal' | 'external';
                internalLink?: (number | null) | AllPage;
                externalLink?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        copyright?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        socialMedia?:
          | {
              platform?: string | null;
              image?: (number | null) | Media;
              /**
               * Enter the full URL, e.g. https://example.com
               */
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'bottomfooter';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: number;
  sections: (
    | {
        images?:
          | {
              /**
               * Upload an image for the topbar.
               */
              image?: (number | null) | Media;
              linkType: 'internal' | 'external';
              internalLink?: {
                relationTo: 'all-pages';
                value: number | AllPage;
              } | null;
              /**
               * Enter the full URL, e.g. https://example.com
               */
              externalLink?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'topbar';
      }
    | {
        items?:
          | {
              icon?: (number | null) | Media;
              text?: string | null;
              internalLink?: {
                relationTo: 'all-pages';
                value: number | AllPage;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'header';
      }
  )[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-subfooter_select".
 */
export interface SiteSubfooterSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'contact-quote'?:
          | T
          | {
              contactMethods?:
                | T
                | {
                    method?:
                      | T
                      | {
                          icon?: T;
                          type?: T;
                          content?: T;
                          id?: T;
                        };
                  };
              quote?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        footerImagesText?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              text?:
                | T
                | {
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bottomfooter?:
          | T
          | {
              bottomfooter?:
                | T
                | {
                    text?:
                      | T
                      | {
                          text?: T;
                          linkType?: T;
                          internalLink?: T;
                          externalLink?: T;
                          id?: T;
                        };
                  };
              copyright?: T;
              socialMedia?:
                | T
                | {
                    platform?: T;
                    image?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        topbar?:
          | T
          | {
              images?:
                | T
                | {
                    image?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        header?:
          | T
          | {
              items?:
                | T
                | {
                    icon?: T;
                    text?: T;
                    internalLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}